# linux-arm64
FROM mcr.microsoft.com/dotnet/runtime:9.0.5-bookworm-slim-arm64v8
COPY Hyprsoft.Dns.Monitor/bin/Release/net9.0/linux-arm64/publish/ app/
ENTRYPOINT ["dotnet", "app/Hyprsoft.Dns.Monitor.dll"]
