# linux-arm64
FROM mcr.microsoft.com/dotnet/runtime:9.0.8-bookworm-slim-arm64v8
WORKDIR /app
COPY Hyprsoft.Dns.Monitor/bin/Release/net9.0/linux-arm64/publish/ .
ENTRYPOINT ["dotnet", "Hyprsoft.Dns.Monitor.dll"]
